{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  namespace: {{ $.Values.global.environment }}
  labels:
    app: {{ $serviceName }}-service
    environment: {{ $.Values.global.environment }}
    {{- include "electronic-paradise.labels" $ | nindent 4 }}
spec:
  type: {{ $service.service.type }}
  ports:
  - port: {{ $service.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq $service.service.type "NodePort") $service.service.nodePort }}
    nodePort: {{ $service.service.nodePort }}
    {{- end }}
  selector:
    app: {{ $serviceName }}-service
    environment: {{ $.Values.global.environment }}
{{- end }}
{{- end }}

---