version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: auth-it-mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "14321:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - auth-it

  user-service-mock:
    container_name: auth-it-user-service-mock
    image: auth-user-service-mock:it
    ports:
      - "3001:3001"
    networks:
      - auth-it

  auth-service:
    container_name: auth-it-auth-service
    image: auth-service:it
    depends_on:
      mssql:
        condition: service_healthy
      user-service-mock:
        condition: service_started
    ports:
      - "5201:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=mssql
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=authdb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - ServiceUrls__UserService=http://user-service-mock:3001
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - auth-it

networks:
  auth-it:
    driver: bridge

