apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: varnex-enterprise
spec:
  selector:
    app: varnex-enterprise-mssql
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql
  type: ClusterIP
