apiVersion: v1
kind: Secret
metadata:
  name: varnex-enterprise-mssql-secret
  namespace: varnex-enterprise
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong@Passw0rd"
  CONNECTION_STRING: "Server=varnex-enterprise-mssql,1433;Database=VarnexEnterpriseDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
