apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: varnex-enterprise-ingress-all
  namespace: varnex-enterprise
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  # Frontend - app.varnex-enterprise.local
  - host: app.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-frontend
            port:
              number: 80
  
  # API Gateway - api.varnex-enterprise.local
  - host: api.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-gateway
            port:
              number: 80
  
  # Auth Service - auth.varnex-enterprise.local
  - host: auth.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-auth
            port:
              number: 80
  
  # User Service - user.varnex-enterprise.local
  - host: user.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-user
            port:
              number: 80
  
  # Product Service - product.varnex-enterprise.local
  - host: product.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-product
            port:
              number: 80
  
  # Order Service - order.varnex-enterprise.local
  - host: order.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-order
            port:
              number: 80
  
  # Payment Service - payment.varnex-enterprise.local
  - host: payment.varnex-enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnex-enterprise-payment
            port:
              number: 80
